# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 05:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import monitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('do_hash', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=200)),
                ('fuzzer_name', models.CharField(max_length=50)),
                ('crash_hash', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('crashlog', models.CharField(max_length=6553500)),
                ('dup_crash', models.IntegerField(default=0)),
                ('reproducable', models.BooleanField(default=True)),
                ('crash_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/crashes/'), upload_to=monitor.models.getUploadPath)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
                ('isopen', models.BooleanField(default=True)),
                ('cve', models.CharField(blank=True, max_length=200, null=True)),
                ('etc_numbering', models.CharField(blank=True, max_length=200, null=True)),
                ('reward', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuzzer_name', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=200)),
                ('crash', models.IntegerField(default=0)),
                ('testcase', models.IntegerField(default=0)),
                ('ping', models.DateTimeField(auto_now=True)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pub_ip', models.CharField(max_length=16)),
                ('pri_ip', models.CharField(max_length=16)),
                ('token', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnetimeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('real_path', models.CharField(max_length=5120)),
                ('is_expired', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/userimage/'), upload_to=monitor.models.getimageUploadPath)),
                ('userkey', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, max_length=10000, null=True)),
                ('use_telegram_alert', models.BooleanField(default=False)),
                ('use_email_alert', models.BooleanField(default=False)),
                ('use_encryption', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_name', models.CharField(max_length=512)),
                ('telegram_bot_key', models.CharField(max_length=512)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fuzzerName', models.CharField(max_length=200)),
                ('binaryName', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('testcase_url', models.CharField(max_length=1024)),
                ('fuzzer_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('fuzzerFile', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/fuzzer/'), upload_to=b'')),
                ('testcaseFile', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/testcase/'), upload_to=b'')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.TelegramBot'),
        ),
    ]
