# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='crash',
            name='crash_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/crashes/'), upload_to=monitor.models.getUploadPath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/userimage/'), upload_to=monitor.models.getimageUploadPath),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='fuzzerFile',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/fuzzer/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcaseFile',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/testcase/'), upload_to=''),
        ),
    ]
