# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
