# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170630_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/userimage/'), upload_to=monitor.models.getimageUploadPath),
        ),
    ]
