# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170912_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_key',
        ),
    ]
