# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170630_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
    ]
