# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_testcase_binaryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
