# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170630_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='comment',
            field=models.CharField(max_length=100000),
        ),
    ]
