# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20170701_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
