# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20170913_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_message',
            field=models.TextField(blank=True, default='[SWEETMON] New crash detected : __title__ / __description__', help_text='__title__ => Crash title, __description__ => Crash log', max_length=10000, null=True),
        ),
    ]
