# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20170702_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_chatid',
            field=models.CharField(blank=True, help_text="To get your chat_id, Add '@get_id_bot' and send '/my_id'", max_length=12, null=True),
        ),
    ]
