# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20170702_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='use_email_alert',
            field=models.BooleanField(default=False, help_text='You should fill out email of your profile to use this feature.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_encryption',
            field=models.BooleanField(default=False, help_text='DEPRECATED FEATURE'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_telegram_alert',
            field=models.BooleanField(default=False, help_text='You should fill out telegram_chatid to use this feature.'),
        ),
    ]
