# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alertinfouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='latest_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='binaryName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='fuzzerFile',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/fuzzer/'), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='fuzzerName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='testcaseFile',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/testcase/'), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crash',
            name='crash_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/crashes/'), upload_to=monitor.models.getUploadPath),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ping',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
