# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_remove_profile_use_encryption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crash',
            old_name='reproducable',
            new_name='reproducible',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='crash',
            new_name='crash_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test_telegram',
        ),
        migrations.AddField(
            model_name='crash',
            name='fuzzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Machine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, help_text='You should fill out this field to use file encryption.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userkey',
            field=models.TextField(blank=True, help_text='Use this key when you regist the new fuzzer.', null=True),
        ),
    ]
