# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20170422_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinformation',
            name='do_hash',
            field=models.BooleanField(default=True),
        ),
    ]
