# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20170713_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='fuzzer_name',
        ),
        migrations.RemoveField(
            model_name='crash',
            name='link',
        ),
        migrations.RemoveField(
            model_name='crash',
            name='target',
        ),
        migrations.AlterField(
            model_name='crash',
            name='comment',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
