# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0015_remove_crash_reproducible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=512)),
                ('email_pw', models.CharField(blank=True, help_text="Note that, password can be decrypted when login to smtp server. So don't use your password.", max_length=512, null=True)),
                ('smtp_server', models.CharField(max_length=512)),
                ('smtp_port', models.CharField(max_length=5)),
                ('is_public', models.BooleanField(default=False, help_text='Check true if you want to share this email')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
