# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_emailbot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
