# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 16:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0017_auto_20170717_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DupCrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_hash', models.CharField(max_length=100)),
                ('dup_crash', models.IntegerField(default=0)),
                ('crash_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/crashes/'), upload_to=monitor.models.getUploadPath)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fuzzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Machine')),
                ('original_crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Crash')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='telegrambot',
            options={},
        ),
    ]
