# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_auto_20170423_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertinfouser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='onetimetoken',
            name='owner',
        ),
    ]
