# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 11:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_auto_20170828_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbot',
            name='smtp_server',
            field=models.CharField(help_text='Check https://www.google.com/settings/security/lesssecureapps if use Gmail', max_length=512),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='fuzzerFile',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/fuzzer/'), upload_to=monitor.models.getFuzzUploadPath),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcaseFile',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/Desktop/Code_Repository/dev_sweetmon/sweetmon/files/testcase/'), upload_to=monitor.models.getFuzzUploadPath),
        ),
    ]
