# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_auto_20170423_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='owner',
        ),
    ]
