# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
