# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_auto_20170423_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telegram_Id',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_alert',
            field=models.BooleanField(default=False),
        ),
    ]
