# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_auto_20170423_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_encrypt',
            field=models.BooleanField(default=False),
        ),
    ]
